### ISSUE TITLE
No issue, but just a tip

### ISSUE THREAD

**Issue by straticsryan** [aman-roy/mp3_downloader#7]
Hey Aman,

Saw your post in the Python Community on Facebook and just took a browse through your source.

It's pretty good. One thing that I would suggest looking into though is the "six" library. That's the encouraged way to handle supporting 2 and 3 in the same library.

For example, all your urllib code is already handled in six. Take a look: https://pythonhosted.org/six/#module-six.moves.urllib.request

Cheers and happy python-ing,

Ryan

**Comment by aman-roy** [comment]
Thanks Ryan. I will consider that.
