### ISSUE TITLE
Allow parameters instead user input

### ISSUE THREAD

**Issue by eusonlito** [aman-roy/mp3_downloader#8]
What about to allow to use script params instead user input?

This will allow to interact with other scripts/daemons.

For example:

```
./program --search "Joe Rogan Experience 1169"
```
```
./program --video "https://www.youtube.com/watch?v=ycPr5-27vSI"
```
```
./program --list list.txt
```

Regards!

**Comment by aman-roy** [comment]
It's a really nice feature to be added. Working on it. Will update the repo ASAP.
Thanks!

**Comment by aman-roy** [comment]
I have updated this repository for flag support.


##### Single song download
```bash
$ ./program.py -s "<song_name>"
```
```bash
$ ./program.py --single "<song_name>"
```

##### List of songs download 

```bash
$ ./program.py -l <filename_with_extension>
```
```bash
$ ./program.py --list <filename_with_extension>
```

Check the latest commits. 
Thanks. :blush: :relaxed:
